// TODO: 상수 정리
export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  NOT_IMPLEMENTED: 501,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const JWT = {
  ACCESS_EXPIRES_IN: process.env.JWT_ACCESS_EXPIRES_IN ?? "1h",
  REFRESH_EXPIRES_IN: process.env.JWT_REFRESH_EXPIRES_IN ?? "14d",
};

export const IMAGE_UPLOAD = {
  MAX_FILE_SIZE_BYTES: 10 * 1024 * 1024,
} as const;
